TEMPLATE = """
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer

import os

from tkinter import *

DIR_NAME = os.path.dirname(__file__)
ASSETS_PATH = os.path.join(DIR_NAME, "{{ assets_path }}")

def rel_path(path):
    # Constructs relative path from gui file
    return os.path.join(DIR_NAME, path)

def rel_asset_path(path):
    # Constructs a relative path from the gui file to an asset
    return os.path.join(ASSETS_PATH, path)
    
window = Tk()

window.geometry("{{ window.width }}x{{ window.height }}")
window.configure(bg = "{{ window.bg_color }}")

canvas = Canvas(
    window,
    bg = "{{ window.bg_color }}",
    height = {{ window.height }},
    width = {{ window.width }},
    bd = 0,
    highlightthickness = 0,
    relief = "ridge")
canvas.place(x = 0, y = 0)
{%- for element in elements -%}
    {{ element.to_code() }}
{%- endfor -%}
window.resizable(False, False)
window.mainloop()
"""
